apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-sd5g
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jmicanek-tenant/devfile-sample-python-basic-1/devfile-sample-python-basic-sd5g@sha256:af507100b8a01dd0e40a11c0d3c21bd8d8d2a1235acf9fa438a2fcef9829e5b7
        name: my-python
        resources: {}
status: {}
